[workspace]
resolver = "2"
members = ["crates/panel", "crates/term", "crates/render", "crates/font", "crates/transport", "crates/fbink-sys", "crates/panel-fbink", "crates/koboterm"]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "GPL-3.0-or-later"

[workspace.dependencies]
panel = { path = "crates/panel" }
term = { path = "crates/term" }
render = { path = "crates/render" }
font = { path = "crates/font" }
transport = { path = "crates/transport" }
fbink-sys = { path = "crates/fbink-sys" }
panel-fbink = { path = "crates/panel-fbink" }
cc = "1"
vt100 = "0.15"
libc = "0.2"
anyhow = "1"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true
