/* automatically generated by rust-bindgen 0.73.2 */

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]

pub type __u16 = ::core::ffi::c_ushort;
pub type __u32 = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fb_fix_screeninfo {
    pub id: [::core::ffi::c_char; 16usize],
    pub smem_start: ::core::ffi::c_ulong,
    pub smem_len: __u32,
    pub type_: __u32,
    pub type_aux: __u32,
    pub visual: __u32,
    pub xpanstep: __u16,
    pub ypanstep: __u16,
    pub ywrapstep: __u16,
    pub line_length: __u32,
    pub mmio_start: ::core::ffi::c_ulong,
    pub mmio_len: __u32,
    pub accel: __u32,
    pub capabilities: __u16,
    pub reserved: [__u16; 2usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fb_bitfield {
    pub offset: __u32,
    pub length: __u32,
    pub msb_right: __u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fb_var_screeninfo {
    pub xres: __u32,
    pub yres: __u32,
    pub xres_virtual: __u32,
    pub yres_virtual: __u32,
    pub xoffset: __u32,
    pub yoffset: __u32,
    pub bits_per_pixel: __u32,
    pub grayscale: __u32,
    pub red: fb_bitfield,
    pub green: fb_bitfield,
    pub blue: fb_bitfield,
    pub transp: fb_bitfield,
    pub nonstd: __u32,
    pub activate: __u32,
    pub height: __u32,
    pub width: __u32,
    pub accel_flags: __u32,
    pub pixclock: __u32,
    pub left_margin: __u32,
    pub right_margin: __u32,
    pub upper_margin: __u32,
    pub lower_margin: __u32,
    pub hsync_len: __u32,
    pub vsync_len: __u32,
    pub sync: __u32,
    pub vmode: __u32,
    pub rotate: __u32,
    pub colorspace: __u32,
    pub reserved: [__u32; 4usize],
}
pub type FBINK_TARGET_T = u8;
pub const FONT_INDEX_E_IBM: FONT_INDEX_E = 0;
pub const FONT_INDEX_E_UNSCII: FONT_INDEX_E = 1;
pub const FONT_INDEX_E_UNSCII_ALT: FONT_INDEX_E = 2;
pub const FONT_INDEX_E_UNSCII_THIN: FONT_INDEX_E = 3;
pub const FONT_INDEX_E_UNSCII_FANTASY: FONT_INDEX_E = 4;
pub const FONT_INDEX_E_UNSCII_MCR: FONT_INDEX_E = 5;
pub const FONT_INDEX_E_UNSCII_TALL: FONT_INDEX_E = 6;
pub const FONT_INDEX_E_BLOCK: FONT_INDEX_E = 7;
pub const FONT_INDEX_E_LEGGIE: FONT_INDEX_E = 8;
pub const FONT_INDEX_E_VEGGIE: FONT_INDEX_E = 9;
pub const FONT_INDEX_E_KATES: FONT_INDEX_E = 10;
pub const FONT_INDEX_E_FKP: FONT_INDEX_E = 11;
pub const FONT_INDEX_E_CTRLD: FONT_INDEX_E = 12;
pub const FONT_INDEX_E_ORP: FONT_INDEX_E = 13;
pub const FONT_INDEX_E_ORPB: FONT_INDEX_E = 14;
pub const FONT_INDEX_E_ORPI: FONT_INDEX_E = 15;
pub const FONT_INDEX_E_SCIENTIFICA: FONT_INDEX_E = 16;
pub const FONT_INDEX_E_SCIENTIFICAB: FONT_INDEX_E = 17;
pub const FONT_INDEX_E_SCIENTIFICAI: FONT_INDEX_E = 18;
pub const FONT_INDEX_E_TERMINUS: FONT_INDEX_E = 19;
pub const FONT_INDEX_E_TERMINUSB: FONT_INDEX_E = 20;
pub const FONT_INDEX_E_FATTY: FONT_INDEX_E = 21;
pub const FONT_INDEX_E_SPLEEN: FONT_INDEX_E = 22;
pub const FONT_INDEX_E_TEWI: FONT_INDEX_E = 23;
pub const FONT_INDEX_E_TEWIB: FONT_INDEX_E = 24;
pub const FONT_INDEX_E_TOPAZ: FONT_INDEX_E = 25;
pub const FONT_INDEX_E_MICROKNIGHT: FONT_INDEX_E = 26;
pub const FONT_INDEX_E_VGA: FONT_INDEX_E = 27;
pub const FONT_INDEX_E_UNIFONT: FONT_INDEX_E = 28;
pub const FONT_INDEX_E_UNIFONTDW: FONT_INDEX_E = 29;
pub const FONT_INDEX_E_COZETTE: FONT_INDEX_E = 30;
pub const FONT_INDEX_E_FONT_MAX: FONT_INDEX_E = 255;
pub type FONT_INDEX_E = ::core::ffi::c_uchar;
pub type FONT_INDEX_T = u8;
pub type FONT_STYLE_T = ::core::ffi::c_int;
pub const ALIGN_INDEX_E_NONE: ALIGN_INDEX_E = 0;
pub const ALIGN_INDEX_E_CENTER: ALIGN_INDEX_E = 1;
pub const ALIGN_INDEX_E_EDGE: ALIGN_INDEX_E = 2;
pub const ALIGN_INDEX_E_ALIGN_MAX: ALIGN_INDEX_E = 255;
pub type ALIGN_INDEX_E = ::core::ffi::c_uchar;
pub type ALIGN_INDEX_T = u8;
pub const PADDING_INDEX_E_NO_PADDING: PADDING_INDEX_E = 0;
pub const PADDING_INDEX_E_HORI_PADDING: PADDING_INDEX_E = 1;
pub const PADDING_INDEX_E_VERT_PADDING: PADDING_INDEX_E = 2;
pub const PADDING_INDEX_E_FULL_PADDING: PADDING_INDEX_E = 3;
pub const PADDING_INDEX_E_MAX_PADDING: PADDING_INDEX_E = 255;
pub type PADDING_INDEX_E = ::core::ffi::c_uchar;
pub type PADDING_INDEX_T = u8;
pub const FG_COLOR_INDEX_E_FG_BLACK: FG_COLOR_INDEX_E = 0;
pub const FG_COLOR_INDEX_E_FG_GRAY1: FG_COLOR_INDEX_E = 1;
pub const FG_COLOR_INDEX_E_FG_GRAY2: FG_COLOR_INDEX_E = 2;
pub const FG_COLOR_INDEX_E_FG_GRAY3: FG_COLOR_INDEX_E = 3;
pub const FG_COLOR_INDEX_E_FG_GRAY4: FG_COLOR_INDEX_E = 4;
pub const FG_COLOR_INDEX_E_FG_GRAY5: FG_COLOR_INDEX_E = 5;
pub const FG_COLOR_INDEX_E_FG_GRAY6: FG_COLOR_INDEX_E = 6;
pub const FG_COLOR_INDEX_E_FG_GRAY7: FG_COLOR_INDEX_E = 7;
pub const FG_COLOR_INDEX_E_FG_GRAY8: FG_COLOR_INDEX_E = 8;
pub const FG_COLOR_INDEX_E_FG_GRAY9: FG_COLOR_INDEX_E = 9;
pub const FG_COLOR_INDEX_E_FG_GRAYA: FG_COLOR_INDEX_E = 10;
pub const FG_COLOR_INDEX_E_FG_GRAYB: FG_COLOR_INDEX_E = 11;
pub const FG_COLOR_INDEX_E_FG_GRAYC: FG_COLOR_INDEX_E = 12;
pub const FG_COLOR_INDEX_E_FG_GRAYD: FG_COLOR_INDEX_E = 13;
pub const FG_COLOR_INDEX_E_FG_GRAYE: FG_COLOR_INDEX_E = 14;
pub const FG_COLOR_INDEX_E_FG_WHITE: FG_COLOR_INDEX_E = 15;
pub const FG_COLOR_INDEX_E_FG_MAX: FG_COLOR_INDEX_E = 255;
pub type FG_COLOR_INDEX_E = ::core::ffi::c_uchar;
pub type FG_COLOR_INDEX_T = u8;
pub const BG_COLOR_INDEX_E_BG_WHITE: BG_COLOR_INDEX_E = 0;
pub const BG_COLOR_INDEX_E_BG_GRAYE: BG_COLOR_INDEX_E = 1;
pub const BG_COLOR_INDEX_E_BG_GRAYD: BG_COLOR_INDEX_E = 2;
pub const BG_COLOR_INDEX_E_BG_GRAYC: BG_COLOR_INDEX_E = 3;
pub const BG_COLOR_INDEX_E_BG_GRAYB: BG_COLOR_INDEX_E = 4;
pub const BG_COLOR_INDEX_E_BG_GRAYA: BG_COLOR_INDEX_E = 5;
pub const BG_COLOR_INDEX_E_BG_GRAY9: BG_COLOR_INDEX_E = 6;
pub const BG_COLOR_INDEX_E_BG_GRAY8: BG_COLOR_INDEX_E = 7;
pub const BG_COLOR_INDEX_E_BG_GRAY7: BG_COLOR_INDEX_E = 8;
pub const BG_COLOR_INDEX_E_BG_GRAY6: BG_COLOR_INDEX_E = 9;
pub const BG_COLOR_INDEX_E_BG_GRAY5: BG_COLOR_INDEX_E = 10;
pub const BG_COLOR_INDEX_E_BG_GRAY4: BG_COLOR_INDEX_E = 11;
pub const BG_COLOR_INDEX_E_BG_GRAY3: BG_COLOR_INDEX_E = 12;
pub const BG_COLOR_INDEX_E_BG_GRAY2: BG_COLOR_INDEX_E = 13;
pub const BG_COLOR_INDEX_E_BG_GRAY1: BG_COLOR_INDEX_E = 14;
pub const BG_COLOR_INDEX_E_BG_BLACK: BG_COLOR_INDEX_E = 15;
pub const BG_COLOR_INDEX_E_BG_MAX: BG_COLOR_INDEX_E = 255;
pub type BG_COLOR_INDEX_E = ::core::ffi::c_uchar;
pub type BG_COLOR_INDEX_T = u8;
pub type DEVICE_ID_T = u16;
pub const WFM_MODE_INDEX_E_WFM_AUTO: WFM_MODE_INDEX_E = 0;
pub const WFM_MODE_INDEX_E_WFM_DU: WFM_MODE_INDEX_E = 1;
pub const WFM_MODE_INDEX_E_WFM_GC16: WFM_MODE_INDEX_E = 2;
pub const WFM_MODE_INDEX_E_WFM_GC4: WFM_MODE_INDEX_E = 3;
pub const WFM_MODE_INDEX_E_WFM_A2: WFM_MODE_INDEX_E = 4;
pub const WFM_MODE_INDEX_E_WFM_GL16: WFM_MODE_INDEX_E = 5;
pub const WFM_MODE_INDEX_E_WFM_REAGL: WFM_MODE_INDEX_E = 6;
pub const WFM_MODE_INDEX_E_WFM_REAGLD: WFM_MODE_INDEX_E = 7;
pub const WFM_MODE_INDEX_E_WFM_GC16_FAST: WFM_MODE_INDEX_E = 8;
pub const WFM_MODE_INDEX_E_WFM_GL16_FAST: WFM_MODE_INDEX_E = 9;
pub const WFM_MODE_INDEX_E_WFM_DU4: WFM_MODE_INDEX_E = 10;
pub const WFM_MODE_INDEX_E_WFM_GL4: WFM_MODE_INDEX_E = 11;
pub const WFM_MODE_INDEX_E_WFM_GL16_INV: WFM_MODE_INDEX_E = 12;
pub const WFM_MODE_INDEX_E_WFM_GCK16: WFM_MODE_INDEX_E = 13;
pub const WFM_MODE_INDEX_E_WFM_GLKW16: WFM_MODE_INDEX_E = 14;
pub const WFM_MODE_INDEX_E_WFM_INIT: WFM_MODE_INDEX_E = 15;
pub const WFM_MODE_INDEX_E_WFM_UNKNOWN: WFM_MODE_INDEX_E = 16;
pub const WFM_MODE_INDEX_E_WFM_INIT2: WFM_MODE_INDEX_E = 17;
pub const WFM_MODE_INDEX_E_WFM_A2IN: WFM_MODE_INDEX_E = 18;
pub const WFM_MODE_INDEX_E_WFM_A2OUT: WFM_MODE_INDEX_E = 19;
pub const WFM_MODE_INDEX_E_WFM_GC16HQ: WFM_MODE_INDEX_E = 20;
pub const WFM_MODE_INDEX_E_WFM_GS16: WFM_MODE_INDEX_E = 21;
pub const WFM_MODE_INDEX_E_WFM_GU16: WFM_MODE_INDEX_E = 22;
pub const WFM_MODE_INDEX_E_WFM_GLK16: WFM_MODE_INDEX_E = 23;
pub const WFM_MODE_INDEX_E_WFM_CLEAR: WFM_MODE_INDEX_E = 24;
pub const WFM_MODE_INDEX_E_WFM_GC4L: WFM_MODE_INDEX_E = 25;
pub const WFM_MODE_INDEX_E_WFM_GCC16: WFM_MODE_INDEX_E = 26;
pub const WFM_MODE_INDEX_E_WFM_GLRC16: WFM_MODE_INDEX_E = 27;
pub const WFM_MODE_INDEX_E_WFM_GC16_PARTIAL: WFM_MODE_INDEX_E = 28;
pub const WFM_MODE_INDEX_E_WFM_GCK16_PARTIAL: WFM_MODE_INDEX_E = 29;
pub const WFM_MODE_INDEX_E_WFM_DUNM: WFM_MODE_INDEX_E = 30;
pub const WFM_MODE_INDEX_E_WFM_P2SW: WFM_MODE_INDEX_E = 31;
pub const WFM_MODE_INDEX_E_WFM_GCCK16: WFM_MODE_INDEX_E = 32;
pub const WFM_MODE_INDEX_E_WFM_GLRCK16: WFM_MODE_INDEX_E = 33;
pub const WFM_MODE_INDEX_E_WFM_MAX: WFM_MODE_INDEX_E = 255;
pub type WFM_MODE_INDEX_E = ::core::ffi::c_uchar;
pub type WFM_MODE_INDEX_T = u8;
pub const HW_DITHER_INDEX_E_HWD_PASSTHROUGH: HW_DITHER_INDEX_E = 0;
pub const HW_DITHER_INDEX_E_HWD_FLOYD_STEINBERG: HW_DITHER_INDEX_E = 1;
pub const HW_DITHER_INDEX_E_HWD_ATKINSON: HW_DITHER_INDEX_E = 2;
pub const HW_DITHER_INDEX_E_HWD_ORDERED: HW_DITHER_INDEX_E = 3;
pub const HW_DITHER_INDEX_E_HWD_QUANT_ONLY: HW_DITHER_INDEX_E = 4;
pub const HW_DITHER_INDEX_E_HWD_LEGACY: HW_DITHER_INDEX_E = 255;
pub type HW_DITHER_INDEX_E = ::core::ffi::c_uchar;
pub type HW_DITHER_INDEX_T = u8;
pub const CFA_MODE_INDEX_E_CFA_DEFAULT: CFA_MODE_INDEX_E = 0;
pub const CFA_MODE_INDEX_E_CFA_AIE_S4: CFA_MODE_INDEX_E = 1;
pub const CFA_MODE_INDEX_E_CFA_AIE_S7: CFA_MODE_INDEX_E = 2;
pub const CFA_MODE_INDEX_E_CFA_AIE_S9: CFA_MODE_INDEX_E = 3;
pub const CFA_MODE_INDEX_E_CFA_G0: CFA_MODE_INDEX_E = 4;
pub const CFA_MODE_INDEX_E_CFA_G1: CFA_MODE_INDEX_E = 5;
pub const CFA_MODE_INDEX_E_CFA_G2: CFA_MODE_INDEX_E = 6;
pub const CFA_MODE_INDEX_E_CFA_NTX: CFA_MODE_INDEX_E = 7;
pub const CFA_MODE_INDEX_E_CFA_NTX_SF: CFA_MODE_INDEX_E = 8;
pub const CFA_MODE_INDEX_E_CFA_SKIP: CFA_MODE_INDEX_E = 9;
pub const CFA_MODE_INDEX_E_CFA_MAX: CFA_MODE_INDEX_E = 255;
pub type CFA_MODE_INDEX_E = ::core::ffi::c_uchar;
pub type CFA_MODE_INDEX_T = u8;
pub const NTX_ROTA_INDEX_E_NTX_ROTA_STRAIGHT: NTX_ROTA_INDEX_E = 0;
pub const NTX_ROTA_INDEX_E_NTX_ROTA_ALL_INVERTED: NTX_ROTA_INDEX_E = 1;
pub const NTX_ROTA_INDEX_E_NTX_ROTA_ODD_INVERTED: NTX_ROTA_INDEX_E = 2;
pub const NTX_ROTA_INDEX_E_NTX_ROTA_SANE: NTX_ROTA_INDEX_E = 3;
pub const NTX_ROTA_INDEX_E_NTX_ROTA_SUNXI: NTX_ROTA_INDEX_E = 4;
pub const NTX_ROTA_INDEX_E_NTX_ROTA_CW_TOUCH: NTX_ROTA_INDEX_E = 5;
pub const NTX_ROTA_INDEX_E_NTX_ROTA_CCW_TOUCH: NTX_ROTA_INDEX_E = 6;
pub const NTX_ROTA_INDEX_E_NTX_ROTA_MAX: NTX_ROTA_INDEX_E = 255;
pub type NTX_ROTA_INDEX_E = ::core::ffi::c_uchar;
pub type NTX_ROTA_INDEX_T = u8;
pub const SUNXI_FORCE_ROTA_INDEX_E_FORCE_ROTA_NOTSUP: SUNXI_FORCE_ROTA_INDEX_E = -128;
pub const SUNXI_FORCE_ROTA_INDEX_E_FORCE_ROTA_CURRENT_ROTA: SUNXI_FORCE_ROTA_INDEX_E = -5;
pub const SUNXI_FORCE_ROTA_INDEX_E_FORCE_ROTA_CURRENT_LAYOUT: SUNXI_FORCE_ROTA_INDEX_E = -4;
pub const SUNXI_FORCE_ROTA_INDEX_E_FORCE_ROTA_PORTRAIT: SUNXI_FORCE_ROTA_INDEX_E = -3;
pub const SUNXI_FORCE_ROTA_INDEX_E_FORCE_ROTA_LANDSCAPE: SUNXI_FORCE_ROTA_INDEX_E = -2;
pub const SUNXI_FORCE_ROTA_INDEX_E_FORCE_ROTA_GYRO: SUNXI_FORCE_ROTA_INDEX_E = -1;
pub const SUNXI_FORCE_ROTA_INDEX_E_FORCE_ROTA_UR: SUNXI_FORCE_ROTA_INDEX_E = 0;
pub const SUNXI_FORCE_ROTA_INDEX_E_FORCE_ROTA_CW: SUNXI_FORCE_ROTA_INDEX_E = 1;
pub const SUNXI_FORCE_ROTA_INDEX_E_FORCE_ROTA_UD: SUNXI_FORCE_ROTA_INDEX_E = 2;
pub const SUNXI_FORCE_ROTA_INDEX_E_FORCE_ROTA_CCW: SUNXI_FORCE_ROTA_INDEX_E = 3;
pub const SUNXI_FORCE_ROTA_INDEX_E_FORCE_ROTA_WORKBUF: SUNXI_FORCE_ROTA_INDEX_E = 4;
pub const SUNXI_FORCE_ROTA_INDEX_E_FORCE_ROTA_MAX: SUNXI_FORCE_ROTA_INDEX_E = 127;
pub type SUNXI_FORCE_ROTA_INDEX_E = ::core::ffi::c_schar;
pub type SUNXI_FORCE_ROTA_INDEX_T = i8;
pub const MTK_SWIPE_DIRECTION_INDEX_E_MTK_SWIPE_DIR_DOWN: MTK_SWIPE_DIRECTION_INDEX_E = 0;
pub const MTK_SWIPE_DIRECTION_INDEX_E_MTK_SWIPE_DIR_UP: MTK_SWIPE_DIRECTION_INDEX_E = 1;
pub const MTK_SWIPE_DIRECTION_INDEX_E_MTK_SWIPE_DIR_LEFT: MTK_SWIPE_DIRECTION_INDEX_E = 2;
pub const MTK_SWIPE_DIRECTION_INDEX_E_MTK_SWIPE_DIR_RIGHT: MTK_SWIPE_DIRECTION_INDEX_E = 3;
pub const MTK_SWIPE_DIRECTION_INDEX_E_MTK_SWIPE_DIR_MAX: MTK_SWIPE_DIRECTION_INDEX_E = 255;
pub type MTK_SWIPE_DIRECTION_INDEX_E = ::core::ffi::c_uchar;
pub type MTK_SWIPE_DIRECTION_INDEX_T = u8;
pub const MTK_HALFTONE_MODE_INDEX_E_MTK_HALFTONE_DISABLED: MTK_HALFTONE_MODE_INDEX_E = 0;
pub const MTK_HALFTONE_MODE_INDEX_E_MTK_HALFTONE_DEFAULT_CHECKER_SIZE: MTK_HALFTONE_MODE_INDEX_E =
    1;
pub const MTK_HALFTONE_MODE_INDEX_E_MTK_HALFTONE_MAX_CHECKER_SIZE: MTK_HALFTONE_MODE_INDEX_E =
    2147483647;
pub type MTK_HALFTONE_MODE_INDEX_E = ::core::ffi::c_uint;
pub type MTK_HALFTONE_MODE_INDEX_T = i32;
pub const FBINK_PXFMT_INDEX_E_FBINK_PXFMT_UNKNOWN: FBINK_PXFMT_INDEX_E = 0;
pub const FBINK_PXFMT_INDEX_E_FBINK_PXFMT_Y4: FBINK_PXFMT_INDEX_E = 4;
pub const FBINK_PXFMT_INDEX_E_FBINK_PXFMT_Y8: FBINK_PXFMT_INDEX_E = 8;
pub const FBINK_PXFMT_INDEX_E_FBINK_PXFMT_BGR565: FBINK_PXFMT_INDEX_E = 16;
pub const FBINK_PXFMT_INDEX_E_FBINK_PXFMT_RGB565: FBINK_PXFMT_INDEX_E = 17;
pub const FBINK_PXFMT_INDEX_E_FBINK_PXFMT_BGR24: FBINK_PXFMT_INDEX_E = 24;
pub const FBINK_PXFMT_INDEX_E_FBINK_PXFMT_RGB24: FBINK_PXFMT_INDEX_E = 25;
pub const FBINK_PXFMT_INDEX_E_FBINK_PXFMT_BGRA: FBINK_PXFMT_INDEX_E = 32;
pub const FBINK_PXFMT_INDEX_E_FBINK_PXFMT_RGBA: FBINK_PXFMT_INDEX_E = 33;
pub const FBINK_PXFMT_INDEX_E_FBINK_PXFMT_BGR32: FBINK_PXFMT_INDEX_E = 34;
pub const FBINK_PXFMT_INDEX_E_FBINK_PXFMT_RGB32: FBINK_PXFMT_INDEX_E = 35;
pub const FBINK_PXFMT_INDEX_E_FBINK_PXFMT_MAX: FBINK_PXFMT_INDEX_E = 255;
pub type FBINK_PXFMT_INDEX_E = ::core::ffi::c_uchar;
pub type FBINK_PXFMT_INDEX_T = u8;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FBInkState {
    pub user_hz: ::core::ffi::c_long,
    pub font_name: *const ::core::ffi::c_char,
    pub view_width: u32,
    pub view_height: u32,
    pub screen_width: u32,
    pub screen_height: u32,
    pub scanline_stride: u32,
    pub bpp: u32,
    pub inverted_grayscale: bool,
    pub device_name: [::core::ffi::c_char; 32usize],
    pub device_codename: [::core::ffi::c_char; 32usize],
    pub device_platform: [::core::ffi::c_char; 32usize],
    pub device_id: DEVICE_ID_T,
    pub pen_fg_color: u8,
    pub pen_bg_color: u8,
    pub screen_dpi: ::core::ffi::c_ushort,
    pub font_w: ::core::ffi::c_ushort,
    pub font_h: ::core::ffi::c_ushort,
    pub max_cols: ::core::ffi::c_ushort,
    pub max_rows: ::core::ffi::c_ushort,
    pub view_hori_origin: u8,
    pub view_vert_origin: u8,
    pub view_vert_offset: u8,
    pub fontsize_mult: u8,
    pub glyph_width: u8,
    pub glyph_height: u8,
    pub is_perfect_fit: bool,
    pub is_mtk: bool,
    pub is_sunxi: bool,
    pub is_tolino: bool,
    pub sunxi_has_fbdamage: bool,
    pub sunxi_force_rota: SUNXI_FORCE_ROTA_INDEX_T,
    pub is_kindle_legacy: bool,
    pub is_kobo_non_mt: bool,
    pub unreliable_wait_for: bool,
    pub can_wake_epdc: bool,
    pub ntx_boot_rota: u8,
    pub ntx_rota_quirk: NTX_ROTA_INDEX_T,
    pub rotation_map: [u8; 4usize],
    pub touch_swap_axes: bool,
    pub touch_mirror_x: bool,
    pub touch_mirror_y: bool,
    pub is_ntx_quirky_landscape: bool,
    pub current_rota: u8,
    pub can_rotate: bool,
    pub can_hw_invert: bool,
    pub has_eclipse_wfm: bool,
    pub has_color_panel: bool,
    pub pixel_format: FBINK_PXFMT_INDEX_T,
    pub can_wait_for_submission: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FBInkConfig {
    pub row: ::core::ffi::c_short,
    pub col: ::core::ffi::c_short,
    pub fontmult: u8,
    pub fontname: FONT_INDEX_T,
    pub is_inverted: bool,
    pub is_flashing: bool,
    pub is_cleared: bool,
    pub is_centered: bool,
    pub hoffset: ::core::ffi::c_short,
    pub voffset: ::core::ffi::c_short,
    pub is_halfway: bool,
    pub is_padded: bool,
    pub is_rpadded: bool,
    pub fg_color: FG_COLOR_INDEX_T,
    pub bg_color: BG_COLOR_INDEX_T,
    pub is_overlay: bool,
    pub is_bgless: bool,
    pub is_fgless: bool,
    pub no_viewport: bool,
    pub is_verbose: bool,
    pub is_quiet: bool,
    pub ignore_alpha: bool,
    pub halign: ALIGN_INDEX_T,
    pub valign: ALIGN_INDEX_T,
    pub scaled_width: ::core::ffi::c_short,
    pub scaled_height: ::core::ffi::c_short,
    pub wfm_mode: WFM_MODE_INDEX_T,
    pub dithering_mode: HW_DITHER_INDEX_T,
    pub sw_dithering: bool,
    pub cfa_mode: CFA_MODE_INDEX_T,
    pub is_nightmode: bool,
    pub no_refresh: bool,
    pub no_merge: bool,
    pub is_animated: bool,
    pub saturation_boost: u8,
    pub to_syslog: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FBInkOTConfig {
    pub font: *mut ::core::ffi::c_void,
    pub margins: FBInkOTConfig__bindgen_ty_1,
    pub style: FONT_STYLE_T,
    pub size_pt: f32,
    pub size_px: ::core::ffi::c_ushort,
    pub is_centered: bool,
    pub padding: PADDING_INDEX_T,
    pub is_formatted: bool,
    pub compute_only: bool,
    pub no_truncation: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FBInkOTConfig__bindgen_ty_1 {
    pub top: ::core::ffi::c_short,
    pub bottom: ::core::ffi::c_short,
    pub left: ::core::ffi::c_short,
    pub right: ::core::ffi::c_short,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FBInkOTFit {
    pub computed_lines: ::core::ffi::c_ushort,
    pub rendered_lines: ::core::ffi::c_ushort,
    pub bbox: FBInkOTFit__bindgen_ty_1,
    pub truncated: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FBInkOTFit__bindgen_ty_1 {
    pub width: ::core::ffi::c_ushort,
    pub height: ::core::ffi::c_ushort,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FBInkRect {
    pub left: ::core::ffi::c_ushort,
    pub top: ::core::ffi::c_ushort,
    pub width: ::core::ffi::c_ushort,
    pub height: ::core::ffi::c_ushort,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FBInkDump {
    pub data: *mut ::core::ffi::c_uchar,
    pub stride: usize,
    pub size: usize,
    pub area: FBInkRect,
    pub clip: FBInkRect,
    pub rota: u8,
    pub bpp: u8,
    pub is_full: bool,
}
unsafe extern "C" {
    pub fn fbink_version() -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn fbink_target() -> FBINK_TARGET_T;
}
unsafe extern "C" {
    pub fn fbink_features() -> u32;
}
unsafe extern "C" {
    pub fn fbink_open() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_close(fbfd: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_init(
        fbfd: ::core::ffi::c_int,
        fbink_cfg: *const FBInkConfig,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_state_dump(fbink_cfg: *const FBInkConfig);
}
unsafe extern "C" {
    pub fn fbink_get_state(fbink_cfg: *const FBInkConfig, fbink_state: *mut FBInkState);
}
unsafe extern "C" {
    pub fn fbink_print(
        fbfd: ::core::ffi::c_int,
        string: *const ::core::ffi::c_char,
        fbink_cfg: *const FBInkConfig,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_add_ot_font(
        filename: *const ::core::ffi::c_char,
        style: FONT_STYLE_T,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_add_ot_font_v2(
        filename: *const ::core::ffi::c_char,
        style: FONT_STYLE_T,
        cfg: *mut FBInkOTConfig,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_free_ot_fonts() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_free_ot_fonts_v2(cfg: *mut FBInkOTConfig) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_print_ot(
        fbfd: ::core::ffi::c_int,
        string: *const ::core::ffi::c_char,
        cfg: *const FBInkOTConfig,
        fbink_cfg: *const FBInkConfig,
        fit: *mut FBInkOTFit,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_printf(
        fbfd: ::core::ffi::c_int,
        ot_cfg: *const FBInkOTConfig,
        fbink_cfg: *const FBInkConfig,
        ot_fit: *mut FBInkOTFit,
        fmt: *const ::core::ffi::c_char,
        ...
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_refresh(
        fbfd: ::core::ffi::c_int,
        region_top: u32,
        region_left: u32,
        region_width: u32,
        region_height: u32,
        fbink_cfg: *const FBInkConfig,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_refresh_rect(
        fbfd: ::core::ffi::c_int,
        rect: *const FBInkRect,
        fbink_cfg: *const FBInkConfig,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_wait_for_submission(fbfd: ::core::ffi::c_int, marker: u32) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_wait_for_complete(fbfd: ::core::ffi::c_int, marker: u32) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_get_last_marker() -> u32;
}
unsafe extern "C" {
    pub fn fbink_is_fb_quirky() -> bool;
}
unsafe extern "C" {
    pub fn fbink_reinit(
        fbfd: ::core::ffi::c_int,
        fbink_cfg: *const FBInkConfig,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_update_verbosity(fbink_cfg: *const FBInkConfig);
}
unsafe extern "C" {
    pub fn fbink_update_pen_colors(fbink_cfg: *const FBInkConfig) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_set_fg_pen_gray(y: u8, quantize: bool, update: bool) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_set_bg_pen_gray(y: u8, quantize: bool, update: bool) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_set_fg_pen_rgba(
        r: u8,
        g: u8,
        b: u8,
        a: u8,
        quantize: bool,
        update: bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_set_bg_pen_rgba(
        r: u8,
        g: u8,
        b: u8,
        a: u8,
        quantize: bool,
        update: bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_print_progress_bar(
        fbfd: ::core::ffi::c_int,
        percentage: u8,
        fbink_cfg: *const FBInkConfig,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_print_activity_bar(
        fbfd: ::core::ffi::c_int,
        progress: u8,
        fbink_cfg: *const FBInkConfig,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_print_image(
        fbfd: ::core::ffi::c_int,
        filename: *const ::core::ffi::c_char,
        x_off: ::core::ffi::c_short,
        y_off: ::core::ffi::c_short,
        fbink_cfg: *const FBInkConfig,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_print_raw_data(
        fbfd: ::core::ffi::c_int,
        data: *const ::core::ffi::c_uchar,
        w: ::core::ffi::c_int,
        h: ::core::ffi::c_int,
        len: usize,
        x_off: ::core::ffi::c_short,
        y_off: ::core::ffi::c_short,
        fbink_cfg: *const FBInkConfig,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_cls(
        fbfd: ::core::ffi::c_int,
        fbink_cfg: *const FBInkConfig,
        rect: *const FBInkRect,
        no_rota: bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_grid_clear(
        fbfd: ::core::ffi::c_int,
        cols: ::core::ffi::c_ushort,
        rows: ::core::ffi::c_ushort,
        fbink_cfg: *const FBInkConfig,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_grid_refresh(
        fbfd: ::core::ffi::c_int,
        cols: ::core::ffi::c_ushort,
        rows: ::core::ffi::c_ushort,
        fbink_cfg: *const FBInkConfig,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_dump(fbfd: ::core::ffi::c_int, dump: *mut FBInkDump) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_region_dump(
        fbfd: ::core::ffi::c_int,
        x_off: ::core::ffi::c_short,
        y_off: ::core::ffi::c_short,
        w: ::core::ffi::c_ushort,
        h: ::core::ffi::c_ushort,
        fbink_cfg: *const FBInkConfig,
        dump: *mut FBInkDump,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_rect_dump(
        fbfd: ::core::ffi::c_int,
        rect: *const FBInkRect,
        dump: *mut FBInkDump,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_restore(
        fbfd: ::core::ffi::c_int,
        fbink_cfg: *const FBInkConfig,
        dump: *const FBInkDump,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_free_dump_data(dump: *mut FBInkDump) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_get_last_rect(rotated: bool) -> FBInkRect;
}
unsafe extern "C" {
    pub fn fbink_button_scan(
        fbfd: ::core::ffi::c_int,
        press_button: bool,
        nosleep: bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_wait_for_usbms_processing(
        fbfd: ::core::ffi::c_int,
        force_unplug: bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_rota_native_to_canonical(rotate: u32) -> u8;
}
unsafe extern "C" {
    pub fn fbink_rota_canonical_to_native(rotate: u8) -> u32;
}
unsafe extern "C" {
    pub fn fbink_invert_screen(
        fbfd: ::core::ffi::c_int,
        fbink_cfg: *const FBInkConfig,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_invert_rect(
        fbfd: ::core::ffi::c_int,
        rect: *const FBInkRect,
        no_rota: bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_get_fb_pointer(
        fbfd: ::core::ffi::c_int,
        buffer_size: *mut usize,
    ) -> *mut ::core::ffi::c_uchar;
}
unsafe extern "C" {
    pub fn fbink_get_fb_info(var_info: *mut fb_var_screeninfo, fix_info: *mut fb_fix_screeninfo);
}
unsafe extern "C" {
    pub fn fbink_set_fb_info(
        fbfd: ::core::ffi::c_int,
        rota: u32,
        bpp: u8,
        grayscale: u8,
        fbink_cfg: *const FBInkConfig,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_fill_rect_gray(
        fbfd: ::core::ffi::c_int,
        fbink_cfg: *const FBInkConfig,
        rect: *const FBInkRect,
        no_rota: bool,
        y: u8,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_fill_rect_rgba(
        fbfd: ::core::ffi::c_int,
        fbink_cfg: *const FBInkConfig,
        rect: *const FBInkRect,
        no_rota: bool,
        r: u8,
        g: u8,
        b: u8,
        a: u8,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_put_pixel_gray(
        fbfd: ::core::ffi::c_int,
        x: u16,
        y: u16,
        v: u8,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_put_pixel_rgba(
        fbfd: ::core::ffi::c_int,
        x: u16,
        y: u16,
        r: u8,
        g: u8,
        b: u8,
        a: u8,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_get_pixel(
        fbfd: ::core::ffi::c_int,
        x: u16,
        y: u16,
        r: *mut u8,
        g: *mut u8,
        b: *mut u8,
        a: *mut u8,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_pack_pixel_gray(y: u8, px: *mut u32) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_pack_pixel_rgba(r: u8, g: u8, b: u8, a: u8, px: *mut u32) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_put_pixel(
        fbfd: ::core::ffi::c_int,
        x: u16,
        y: u16,
        px: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_fill_rect(
        fbfd: ::core::ffi::c_int,
        fbink_cfg: *const FBInkConfig,
        rect: *const FBInkRect,
        no_rota: bool,
        px: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_wakeup_epdc() -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_sunxi_toggle_ntx_pen_mode(
        fbfd: ::core::ffi::c_int,
        toggle: bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_sunxi_ntx_enforce_rota(
        fbfd: ::core::ffi::c_int,
        mode: SUNXI_FORCE_ROTA_INDEX_T,
        fbink_cfg: *const FBInkConfig,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_mtk_set_swipe_data(
        direction: MTK_SWIPE_DIRECTION_INDEX_T,
        steps: u8,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_wait_for_any_complete(fbfd: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_mtk_set_halftone(
        fbfd: ::core::ffi::c_int,
        exclude_regions: *const FBInkRect,
        size: MTK_HALFTONE_MODE_INDEX_T,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_mtk_toggle_auto_reagl(
        fbfd: ::core::ffi::c_int,
        toggle: bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fbink_mtk_toggle_pen_mode(fbfd: ::core::ffi::c_int, toggle: bool) -> ::core::ffi::c_int;
}
pub type INPUT_DEVICE_TYPE_T = u32;
pub type INPUT_SETTINGS_TYPE_T = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FBInkInputDevice {
    pub type_: INPUT_DEVICE_TYPE_T,
    pub fd: ::core::ffi::c_int,
    pub matched: bool,
    pub name: [::core::ffi::c_char; 256usize],
    pub path: [::core::ffi::c_char; 4096usize],
}
unsafe extern "C" {
    pub fn fbink_input_scan(
        match_types: INPUT_DEVICE_TYPE_T,
        exclude_types: INPUT_DEVICE_TYPE_T,
        settings: INPUT_SETTINGS_TYPE_T,
        dev_count: *mut usize,
    ) -> *mut FBInkInputDevice;
}
unsafe extern "C" {
    pub fn fbink_input_check(
        filepath: *const ::core::ffi::c_char,
        match_types: INPUT_DEVICE_TYPE_T,
        exclude_types: INPUT_DEVICE_TYPE_T,
        settings: INPUT_SETTINGS_TYPE_T,
    ) -> *mut FBInkInputDevice;
}
