[package]
name = "koboterm"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "koboterm"
path = "src/main.rs"

[dependencies]
panel.workspace = true
term.workspace = true
render.workspace = true
font.workspace = true
transport.workspace = true
ui.workspace = true
anyhow.workspace = true
libc.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
panel-fbink.workspace = true
input.workspace = true
